import type { ModelCategory, WeightKey, SignalRule, ModelProfile } from '../types'

export const MIN_SCORE = 0.08

export const quickPrompts = [
  'Best cheap model for customer support chat',
  'Private coding assistant for our internal repo',
  'Long PDF contract analysis with high accuracy',
  'Generate product images for an ecommerce campaign',
  'Fast realtime voice agent for appointments',
  'Video model for short social ads',
]

export const categoryLabels: Record<ModelCategory, string> = {
  general: 'General',
  code: 'Code',
  image: 'Image',
  video: 'Video',
  voice: 'Voice',
  music: 'Music',
  document: 'Document',
}

export const defaultWeights: Record<WeightKey, number> = {
  quality: 1.25,
  affordability: 0.75,
  speed: 0.7,
  context: 0.65,
  privacy: 0.55,
  availability: 0.6,
}

export const signalRules: SignalRule[] = [
  {
    id: 'budgetSensitive',
    label: 'Budget sensitive',
    pattern: /(cheap|budget|cost|affordable|high volume|scale|low price|inexpensive)/,
    weights: { affordability: 0.9 },
  },
  {
    id: 'speedSensitive',
    label: 'Speed sensitive',
    pattern: /(fast|speed|latency|realtime|real time|instant|support|call|live)/,
    weights: { speed: 0.75 },
  },
  {
    id: 'qualitySensitive',
    label: 'Quality sensitive',
    pattern: /(best|accurate|quality|high stakes|legal|medical|finance|reasoning|critical|reliable)/,
    weights: { quality: 1.2, affordability: -0.35 },
  },
  {
    id: 'longContext',
    label: 'Long context',
    pattern: /(long|pdf|document|context|book|repo|many files|contract|thesis|manual)/,
    weights: { context: 0.85 },
  },
  {
    id: 'privacySensitive',
    label: 'Privacy sensitive',
    pattern: /(private|privacy|self-host|self host|local|offline|internal|sensitive|secure|confidential)/,
    weights: { privacy: 1.05 },
  },
]

// Provider logo URLs
export const providerLogos: Record<string, string> = {
  'openai': 'https://cdn.worldvectorlogo.com/logos/openai-2.svg',
  'anthropic': 'https://upload.wikimedia.org/wikipedia/commons/7/78/Anthropic_logo.svg',
  'google': 'https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690b6.svg',
  'deepseek': 'https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/dark/deepseek-color.png',
  'hugging face': 'https://huggingface.co/front/assets/huggingface_logo-noborder.svg',
  'stability': 'https://images.crunchbase.com/image/upload/c_pad,h_40,w_40,f_auto,q_auto:eco,dpr_1/v1669768198/hrrh5csxlojrdsdz5tpy.png',
  'runway': 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Runway_AI_logo.png',
  'elevenlabs': 'https://images.crunchbase.com/image/upload/c_pad,h_40,w_40,f_auto,q_auto:eco,dpr_1/rclwq0gxrpsxvfhbnsga.png',
  'cohere': 'https://images.crunchbase.com/image/upload/c_pad,h_40,w_40,f_auto,q_auto:eco,dpr_1/v1488397626/bwwxusmuigk2dcuphzij.png',
  'suno': 'https://images.crunchbase.com/image/upload/c_pad,h_40,w_40,f_auto,q_auto:eco,dpr_1/dydac0rgixm20dw2lgbm.png',
  'mistral': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Mistral_AI_logo_%282025%29.svg',
  'meta': 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Meta-Logo.png',
  'black forest': 'https://cdn.prod.website-files.com/66f383c1a1ba3e4fa0c61ed6/66f39fa17d3f2d0be3cc5d80_BFL_icon.svg',
}

export function getProviderLogo(provider: string): string | null {
  const providerLower = provider.toLowerCase()
  for (const [key, url] of Object.entries(providerLogos)) {
    if (providerLower.includes(key)) return url
  }
  // Fallback: try first word
  const firstWord = providerLower.split(/[\s/]/)[0]
  if (providerLogos[firstWord]) return providerLogos[firstWord]
  return null
}

// Fallback seed data in case API server is unreachable
export const localModelRegistry: ModelProfile[] = [
  {
    id: 'frontier-generalist',
    name: 'Frontier Generalist API',
    provider: 'OpenAI / Anthropic / Google class',
    category: 'general',
    access: 'API',
    modalities: ['text', 'vision', 'tools'],
    bestFor: 'High stakes reasoning, planning, rich conversation, and mixed knowledge work.',
    source: 'Seed registry',
    sourceUrl: 'https://openrouter.ai/api/v1/models',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.76,
    pricing: { unit: 'estimated', inputPerMillion: 5, outputPerMillion: 15 },
    contextLength: 200000,
    metrics: { quality: 0.94, affordability: 0.46, speed: 0.62, context: 0.88, privacy: 0.54, availability: 0.9 },
  },
  {
    id: 'fast-generalist',
    name: 'Fast Generalist API',
    provider: 'OpenRouter multi-provider route',
    category: 'general',
    access: 'API',
    modalities: ['text', 'tools'],
    bestFor: 'Customer support, summarization, research triage, and high volume chat.',
    source: 'Seed registry',
    sourceUrl: 'https://openrouter.ai/api/v1/models',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.78,
    pricing: { unit: 'estimated', inputPerMillion: 0.25, outputPerMillion: 1.0 },
    contextLength: 128000,
    metrics: { quality: 0.76, affordability: 0.86, speed: 0.92, context: 0.7, privacy: 0.5, availability: 0.88 },
  },
  {
    id: 'code-specialist',
    name: 'Code Specialist Model',
    provider: 'OpenAI / Anthropic / DeepSeek class',
    category: 'code',
    access: 'API',
    modalities: ['text', 'code', 'tools'],
    bestFor: 'Repository edits, debugging, test generation, migrations, and code review.',
    source: 'Seed registry',
    sourceUrl: 'https://openrouter.ai/api/v1/models',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.74,
    pricing: { unit: 'estimated', inputPerMillion: 2.0, outputPerMillion: 8.0 },
    contextLength: 200000,
    metrics: { quality: 0.9, affordability: 0.58, speed: 0.68, context: 0.84, privacy: 0.48, availability: 0.82 },
  },
  {
    id: 'open-code',
    name: 'Open Code Model',
    provider: 'Hugging Face ecosystem',
    category: 'code',
    access: 'Open source',
    modalities: ['text', 'code'],
    bestFor: 'Self-hosted developer tools, internal code search, and private repos.',
    source: 'Seed registry',
    sourceUrl: 'https://huggingface.co/models',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.7,
    pricing: { unit: 'infrastructure', inputPerMillion: 0, outputPerMillion: 0 },
    contextLength: 64000,
    metrics: { quality: 0.72, affordability: 0.93, speed: 0.66, context: 0.62, privacy: 0.92, availability: 0.74 },
  },
  {
    id: 'image-creator',
    name: 'Image Generation Studio',
    provider: 'OpenAI / Stability / Black Forest class',
    category: 'image',
    access: 'API',
    modalities: ['image', 'editing'],
    bestFor: 'Product imagery, campaigns, concept art, editing, and style exploration.',
    source: 'Seed registry',
    sourceUrl: 'https://huggingface.co/models?pipeline_tag=text-to-image',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.68,
    pricing: { unit: 'estimated', inputPerMillion: 0, outputPerMillion: 0 },
    contextLength: 8000,
    metrics: { quality: 0.88, affordability: 0.6, speed: 0.72, context: 0.42, privacy: 0.48, availability: 0.8 },
  },
  {
    id: 'video-creator',
    name: 'Video Generation Model',
    provider: 'Runway / Google / OpenAI class',
    category: 'video',
    access: 'API',
    modalities: ['video', 'image'],
    bestFor: 'Short cinematic clips, ads, storyboards, product shots, and motion tests.',
    source: 'Seed registry',
    sourceUrl: 'https://huggingface.co/models?pipeline_tag=image-to-video',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.58,
    pricing: { unit: 'estimated', inputPerMillion: 0, outputPerMillion: 0 },
    contextLength: 8000,
    metrics: { quality: 0.84, affordability: 0.34, speed: 0.32, context: 0.36, privacy: 0.42, availability: 0.58 },
  },
  {
    id: 'voice-agent',
    name: 'Realtime Voice Stack',
    provider: 'OpenAI / ElevenLabs / Deepgram class',
    category: 'voice',
    recordType: 'strategy_template',
    sourceAuthority: 'seed',
    linkStatus: 'catalog',
    primaryUseCases: ['voice'],
    secondaryUseCases: ['speech_to_text', 'text_to_speech'],
    access: 'API',
    modalities: ['audio', 'speech', 'text'],
    bestFor: 'Voice agents, narration, transcription, dubbing, and conversational audio.',
    source: 'Seed registry',
    sourceUrl: 'https://huggingface.co/models?pipeline_tag=automatic-speech-recognition',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.66,
    pricing: { unit: 'estimated', inputPerMillion: 0, outputPerMillion: 0 },
    contextLength: 16000,
    metrics: { quality: 0.83, affordability: 0.64, speed: 0.88, context: 0.5, privacy: 0.5, availability: 0.76 },
  },
  {
    id: 'music-generator',
    name: 'Music Generation Model',
    provider: 'Suno / Udio class',
    category: 'music',
    access: 'API',
    modalities: ['audio', 'music'],
    bestFor: 'Song sketches, background tracks, sonic branding, and creative ideation.',
    source: 'Seed registry',
    sourceUrl: 'https://huggingface.co/models?pipeline_tag=text-to-audio',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.52,
    pricing: { unit: 'estimated', inputPerMillion: 0, outputPerMillion: 0 },
    contextLength: 8000,
    metrics: { quality: 0.8, affordability: 0.52, speed: 0.56, context: 0.28, privacy: 0.38, availability: 0.62 },
  },
  {
    id: 'document-intelligence',
    name: 'Document Intelligence Model',
    provider: 'Google / OpenAI / Mistral class',
    category: 'document',
    access: 'API',
    modalities: ['text', 'vision', 'ocr'],
    bestFor: 'Long PDFs, OCR, extraction, compliance checks, and document Q&A.',
    source: 'Seed registry',
    sourceUrl: 'https://openrouter.ai/api/v1/models',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.7,
    pricing: { unit: 'estimated', inputPerMillion: 1.25, outputPerMillion: 5.0 },
    contextLength: 1000000,
    metrics: { quality: 0.86, affordability: 0.62, speed: 0.7, context: 0.94, privacy: 0.56, availability: 0.78 },
  },
  {
    id: 'private-open-general',
    name: 'Private Open Generalist',
    provider: 'Hugging Face / local inference',
    category: 'general',
    access: 'Open source',
    modalities: ['text'],
    bestFor: 'Private workflows, internal copilots, offline use, and custom fine-tuning.',
    source: 'Seed registry',
    sourceUrl: 'https://huggingface.co/models',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.68,
    pricing: { unit: 'infrastructure', inputPerMillion: 0, outputPerMillion: 0 },
    contextLength: 32000,
    metrics: { quality: 0.68, affordability: 0.9, speed: 0.58, context: 0.58, privacy: 0.98, availability: 0.7 },
  },
  {
    id: 'embedding-rerank-stack',
    name: 'Embedding + Rerank Stack',
    provider: 'Cohere / Jina / OpenAI class',
    category: 'document',
    recordType: 'strategy_template',
    sourceAuthority: 'seed',
    linkStatus: 'catalog',
    primaryUseCases: ['document'],
    secondaryUseCases: ['embedding', 'reranking'],
    access: 'API',
    modalities: ['embedding', 'rerank', 'text'],
    bestFor: 'Search, RAG retrieval, semantic clustering, deduplication, and document matching.',
    source: 'Seed registry',
    sourceUrl: 'https://huggingface.co/models?pipeline_tag=sentence-similarity',
    lastVerified: '2026-06-26T00:00:00.000Z',
    confidence: 0.64,
    pricing: { unit: 'estimated', inputPerMillion: 0.1, outputPerMillion: 0 },
    contextLength: 8192,
    metrics: { quality: 0.78, affordability: 0.88, speed: 0.9, context: 0.46, privacy: 0.58, availability: 0.82 },
  },
]
